import { writable } from "svelte/store";
import moment from "moment";

export let form = writable({ id: 0,
     epiWk: 0, 
     dateReq: moment().format('yyyy-MM-DD'), 
     sex: '', 
     age: '', 
     surname: '', 
     name:'',
     hospital:'',
     ward:'',
     card:'', 
     rapid_test:'',
     symptoms:'',
     vaccinated:false,
     dose:0,
     vaccine_type:'',
     pcr:'',
     case:'',
     n_gene:false,
     e_gene:false,
     results: {
        date_tested:moment().format('yyyy-MM-DD'), 
        delY144_al_1:false,
        q498r:false,
        s_gene:false,
        variant:'',
        p681r:false,
        d215g:false,
        d614g:false,
        k417n:false,
        ngs:'', 
        crick:'', 
        nicd:''
     },
     result_pcr:'',
     comments:[{user:'',message:''}],
     test_id:0,
     sample_id:0,
     order_id:0,
     exist:false
    })

    export function resetForm(){
      form.set({ id: 0,
         epiWk: 0, 
         dateReq: moment().format('yyyy-MM-DD'), 
         sex: '', 
         age: '', 
         surname: '', 
         name:'',
         hospital:'',
         ward:'',
         card:'', 
         rapid_test:'',
         symptoms:'',
         vaccinated:false,
         dose:0,
         vaccine_type:'',
         pcr:'',
         case:'',
         n_gene:false,
         e_gene:false,
         results: {
            date_tested:moment().format('yyyy-MM-DD'), 
            delY144_al_1:false,
            q498r:false,
            s_gene:false,
            variant:'',
            p681r:false,
            d215g:false,
            d614g:false,
            k417n:false,
            ngs:'', 
            crick:'', 
            nicd:''
         },
         result_pcr:'',
         comments:[{user:'',message:''}],
         test_id:0,
         sample_id:0,
         order_id:0,
         exist:false
        })
    }